### ISSUE TITLE
G - Display a Globe

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#13]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to see a globe with markers (of diving spots)
**to be able to** have a better overview of existing diving spots

# Description

Display an interactive globe with clickable markers, that show Geo-Tags of their position

# Acceptance Criteria

- [ ] A globe shall be displayed
- [ ] The globe shall be zoomable and movable (360°)
- [ ] Markers shall mark diving spots and be clickable
- [ ] When a marker is clicked, the Geo-Tags of the diving spot shall be displayed

# Tasks

(for developers team)

- [ ] Crate a new branch
- [ ] Install cesium and create a basic globe
- [ ] Implement all necessary components etc. for a 3D-Globe with Cesium
- [ ] Hide the bottom of the default cesium-display
- [ ] Display marker of diving spots
- [ ] Implement display of GeoTags by click on marker
- [ ] Add storybook
- [ ] Add tests

# Complexity
XL

**Comment by NilsHolthey** [comment]
Hi Irene, nice user-story.
I think you should be more specific with the "necessary components". (no etc.)

**Comment by irenepapaspyratos** [comment]
Hi Nils, this changes have been made only to light up your morning! 🥰
