### ISSUE TITLE
H - Display Marker for Diving-Spots on Globus

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#15]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to see markers on the globe
**to be able to** have a better overview of existing diving spots all over the world

# Description

Display an interactive globe

# Acceptance Criteria

- [ ] Markers shall be displayed to show the location of the diving spots
- [ ] Every diving spot shall have one marker
- [ ] Markers shall be scaled while zooming the globe

# Tasks

- [ ] Crate a new branch
- [ ] Add Zustand to be able to use the marker's positions everywhere in the code
- [ ] Add entities or flat ellipsoids as markers to the globe for every spot
- [ ] Adjust all necessary files

# Complexity
M
