### ISSUE TITLE
I - Create Form to add new diving-spots

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#16]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to have a form to add/edit spots 
**to be able to** extend the database for the community

# Description

Add a page to add/edit entries

# Acceptance Criteria

- [ ] A form to add and one to edit is displayed on it's corresponding page
- [ ] All necessary fields are existing -empty for adding, filled with data for editing- in the form
- [ ] A submit-button exists, that stores the changes on click

# Tasks

- [ ] Create a new branch
- [ ] Create a form reusable component
- [ ] Create corresponding pages
- [ ] Add component to app
- [ ] Add storybook
- [ ] Add tests

# Complexity
XL
