### ISSUE TITLE
J - Create Navigation for globe's alternative display => Lists of linked spots, animals & organizers

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#18]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to have separate pages and a navigation-bar 
**to be able to** switch between the globe- and a list-display of spots, animals and entries

# Description

Add a lasting navigation-bar at the bottom of the screen with at least one clickable element to switch between globe- and list-pages

# Acceptance Criteria

- [ ] Globe-view and list-views shall be on different pages
- [ ] At the bottom of the screen a nav-bar is shown always with at least one clickable element to switch and one to go back to the homepage (initial view => globe)
- [ ] Upon clicking the corresponding element, a redirect occurs to the related page 

# Tasks

- [ ] Create a page for each view (globe => index)
- [ ] Create corresponding api-pages (incl. id-assignment where necessary)
- [ ] Add corresponding components to app
- [ ] Add storybook
- [ ] Add tests

# Complexity
XL

**Comment by NilsHolthey** [comment]
Looks good to me!
