### ISSUE TITLE
K - Implement Links from PopUp-Items to Item-Displays

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#19]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to have linked items in the marker-popUps
**to be able to** see detailed information

# Description

Add links to mentioned animals and organizers in each marker-popUp

# Acceptance Criteria

- [ ] Each mentioned animal/organizer leads to it's detail-page on click

# Tasks

- [ ] Create new branch
- [ ] implement links for each animal/organizer in each marker-popUp

# Complexity
S
