### ISSUE TITLE
M - Implement add-button (Navigation)

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#23]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to have an add-button in the navigation-bar
**to be able to** add quickly a new entry

# Description

Add an add-button to the navigation-bar

# Acceptance Criteria

- [ ] A clickable element exists in the navigation-bar
- [ ] A click on this element redirects the user to the page with the add/edit-form

# Tasks

- [ ] Create a new branch
- [ ] Create a new element in the nav-bar
- [ ] Implement redirecting to the form-page on click
- [ ] Add tests

# Complexity
XL

**Comment by UrsulaMontag** [comment]
Do you really want to redirect to create-form-page or maybe direct the user to a new page edit-form which just render the same form component with default item data?
