### ISSUE TITLE
N - Implement edit-button (Detail-Displays)

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#24]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to have an edit-button
**to be able to** edit quickly an entry

# Description

Add an edit-button to the navigation-bar

# Acceptance Criteria

- [ ] A clickable element exists to edit an entry
- [ ] A click on this element redirects the user to the page with the add/edit-form

# Tasks

- [ ] Create a new branch
- [ ] Create a new element to click on
- [ ] Implement redirecting to the form-page on click


# Complexity
XL
