### ISSUE TITLE
O - Implement delete-button (only Organizer, Spot: Warning=>Edit only, Animal: Warning=>Edit only)

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#25]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to have a. delete-button in the navigation-bar
**to be able to** delete quickly an entry

# Description

Add a delete-button 

# Acceptance Criteria

- [ ] A clickable element exists to delete an element
- [ ] A click on this element deletes the entry

# Tasks

- [ ] Create a new branch
- [ ] Create a new element to click on
- [ ] Implement deleting on click

# Complexity
XL
