### ISSUE TITLE
P - Add MongoDB

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#26]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to have a independent database for adding my entries
**to be able to** extend the displayed data for the community

# Description

Add connection to MongoDB Atlas

# Acceptance Criteria

- [ ] MongoDB Atlas connects with app
- [ ] Entries are able to be deleted, added and edited

# Tasks

- [ ] Create a new branch
- [ ] Add necessary files
- [ ] Check connectivity

# Complexity
L

**Comment by aclaes** [comment]
Hi Irene,

The complexity of this story sould be XXXXXXL. 

If I’m not mistaking you don’t have functionality yet to add /edit/delete entries.

I strongly(!) advise to create various separated user stories for this. Mixing all the interactive features up together with the database connection is a very heavy lifting.

Your user stories might be structured liked this
- Add MongoDB connection (write from developer view, indeptendent data storage)
- Add spot
- Edit Spot
- Delete Spot
- Add Animal
- Edit Animal
- Delete Animal
- Add Organizer
- Edit Organizer
- Delete Organizer

Having small stories you can work on one after another will be way easier.

**Comment by irenepapaspyratos** [comment]
Was already separated, here only the connection will be implemented
