### ISSUE TITLE
E - Display a list of animals

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#6]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to see a list of animals 
**to be able to** get a better overview of with which wild animals I can dive accompanied

# Description

A list of the single animals shall be shown, where each animal is displayed only with it's name as a link to open it's details-display.

# Acceptance Criteria

- [ ] Each animal should be visually separated
- [ ] Each animal should be linking to the page/component with the important details of this animal (see issues #2 )
- [ ] All available animal should be displayed

# Tasks

- [ ] Create a data structure to hold an array of multiple animals
- [ ] Create a component to render the list of animals
- [ ] The component receives the array via props
- [ ] Add a test to check if all given spots are rendered
- [ ] Add component to app
- [ ] Add to Storybook
- [ ] Add basic styling

# Complexity
S
