### ISSUE TITLE
F - Display a list of organizers

### ISSUE THREAD

**Issue by irenepapaspyratos** [irenepapaspyratos/capstone-project#7]

**Comment by irenepapaspyratos** [comment]
# Value Proposition

**As a** diver
**I need** to see a list of organizers
**to be able to** get a better overview of with whom I can dive accompanied with wild animals 

# Description

A list of the single organizer shall be shown, where each organizer is displayed only with it's name as a link to open it's details-display.

# Acceptance Criteria

- [ ] Each organizer should be visually separated
- [ ] Each organizer should be linking to the page/component with the important details of this organizer (see issues #4 )
- [ ] All available organizers should be displayed

# Tasks

- [ ] Create a data structure to hold an array of multiple organizers
- [ ] Create a component to render the list of organizers
- [ ] The component receives the array via props
- [ ] Add a test to check if all given organizers are rendered
- [ ] Add component to app
- [ ] Add to Storybook
- [ ] Add basic styling

# Complexity
S
